INSERT INTO product_type (name_product_type)
VALUES ("Doces"),
       ("Cereais"),
       ("Hortifruti"),
       ("Bolachas e Biscoitos"),
       ("Massas"),
       ("Temperos e Condimentos"),
       ("Laticíneos"),
       ("Friamberia"),
       ("Açougue"),
       ("Padaria"),
       ("Higiene Pessoal"),
       ("Bebidas"),
       ("Bebidas Alcoólicas"),
       ("Limpeza"),
       ("Outros");